node {

        stage('Checkout') {
            git url: 'https://github.com/basivireddy/microservice-app-example.git', credentialsId: 'github-basivireddy', branch: 'master'
        }

        
	stage('Docker Build and Publish') {
		buildAndPush( "${env.JOB_NAME}", 'v1');
    }
		

	
}


def buildAndPush( imageName, version){
    def app
    try {
	    dir ('log-message-processor') {
		    
		    app = docker.build("private-registry:5000/${imageName}")
		
		app.push("${version}.${env.BUILD_NUMBER}")
		
             		    
	    }
	    
	} catch (error){
		sh 'echo "Not able to build and push docker image ${error}"'
	}
}
