node {

        stage('Checkout') {
            git url: 'https://github.com/basivireddy/microservice-app-example.git', credentialsId: 'github-basivireddy', branch: 'master'
        }

        
	stage('Docker Build and Publish') {
		buildAndPush( "${env.JOB_NAME}", 'v1');
    }
		

	
}


def buildAndPush( imageName, version){
   
	   
		    
		    sh 'docker build -t private-registry:5000/log-message-processor:v1.0 log-message-processor/'
		    sh 'docker push private-registry:5000/log-message-processor:v1.0'
		
             		    
	
	
}
